// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorSmoothScroll
{
    internal sealed partial class Vsix
    {
        public const string Id = "Ch0pstix.VSExtensions.EditorSmoothScroll";
        public const string Name = "Editor Smooth Scroll";
        public const string Description = @"Enables smooth pixel scrolling in the editor text view.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Ch0pstix";
        public const string Tags = "";
    }
}
