// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorSmoothScroll
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EditorSmoothScrollString = "735a23ee-71fa-4b1e-893b-eda8f46a36a9";
        public static Guid EditorSmoothScroll = new Guid(EditorSmoothScrollString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ExtensionMenu = 0x1100;
        public const int ExtensionMenuGroup = 0x1150;
        public const int OptionsCommand = 0x0100;
    }
}